name: ebop_maven
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8

  # optional CUDNN for TensorFlow/Keras 2.6+ to see & use my Nvidia GPU
  - cudnn=8.1

  - pip
  - pip:
    - -r requirements.txt
variables:
  JKTEBOP_DIR: ~/jktebop43
  TF_CPP_MIN_LOG_LEVEL: 2         # Suppress TF info/warn messages
