name: ebop_maven
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9

  # optional CUDNN for TensorFlow/Keras to see & use Nvidia GPU
  # see https://www.tensorflow.org/install/source#gpu for compatibility list
  - cudnn

  # support for keras.utils.plot_model()
  - pydot=1.4
  - graphviz=8.0

  - pip
  - pip:
    - -r requirements.txt
variables:
  JKTEBOP_DIR: ~/jktebop/
  TF_CPP_MIN_LOG_LEVEL: 2         # Suppress TF info/warn messages
