[project]
name = "ebop_maven"
version = "0.0.1-alpha"
description = "EBOP Model Automatic input Value Estimation Neural network"

[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"